# yamllint disable rule:line-length

name: Main workflow

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: 0 0 * * 5

jobs:
  test_wsl_v1:
    name: Test WSLv1
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install WSLv1
        uses: Vampire/setup-wsl@v1

      - name: Install dependencies
        shell: wsl-bash -u root {0}
        run: |
          sudo apt-get update
          sudo apt-get -y install fish git ca-certificates curl nodejs

      - name: Update CA certificates
        shell: wsl-bash -u root {0}
        run: update-ca-certificates

      - name: Run tests
        shell: wsl-bash -u root {0}
        run: |
          npm install --include=dev --verbose
          find node_modules
          npm link bats --verbose
          npm ls --verbose
          npm run test --verbose

  test_windows:
    name: Test Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Run tests
        shell: bash
        run: |
          npm install --include=dev --verbose
          find node_modules
          npm link bats --verbose
          npm ls --verbose
          npm run test --verbose
