name: Main workflow

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  # schedule:
  #   - cron: 0 0 * * 5

jobs:
  test_wsl:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install WSLv1
        uses: Vampire/setup-wsl@v1
        with:
          additional-packages: fish git ca-certificates

      - uses: actions/setup-node@v2

      - name: Install bats-core & bats-assert
        shell: wsl-bash -u root {0}
        run: |
          update-ca-certificates
          npm i -g bats@^1.2.1 bats-assert@v2.0.0

      - name: Run tests
        shell: wsl-bash -u root {0}
        env:
          GITHUB_API_TOKEN: ${{ github.token }}
        run: bats test

  test_msys2:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2

      - name: Install bats-core & bats-assert
        run: npm i -g bats@^1.2.1 bats-assert@v2.0.0

      - name: Run tests
        env:
          GITHUB_API_TOKEN: ${{ github.token }}
        run: bats test

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Install shfmt & shellcheck
        run: brew install shfmt shellcheck

      - name: Install lintball
        run: curl -o- https://raw.githubusercontent.com/elijahr/lintball/devel/install.sh | bash

      - name: Check
        run: check-all
