# yamllint disable rule:line-length

name: Main workflow

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: 0 0 * * 5

jobs:
  test_wsl:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install WSLv1
        uses: Vampire/setup-wsl@v1

      - name: Install dependencies
        shell: wsl-bash -u root {0}
        run: |
          sudo apt-get update
          sudo apt-get -y install fish git ca-certificates curl

      - name: Update CA certificates
        shell: wsl-bash -u root {0}
        run: update-ca-certificates

      - name: Install bats
        shell: wsl-bash -u root {0}
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
          # export NVM_DIR="$HOME/.nvm"
          # [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

      - name: Run tests
        shell: wsl-bash -u root {0}
        run: |
          nvm install node
          nvm use node
          npm install --include=dev
          npm run test

  test_msys2:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      - name: Run tests
        shell: bash
        run: |
          npm install --include=dev
          npm run test
